CREATE TABLE IF NOT EXISTS `0_product_shipping_attributes` (
  `stock_id`               VARCHAR(32)    NOT NULL,
  `length`                 DECIMAL(10,3)  NULL,
  `width`                  DECIMAL(10,3)  NULL,
  `height`                 DECIMAL(10,3)  NULL,
  `dim_unit`               ENUM('cm','in') NOT NULL DEFAULT 'cm',
  `weight`                 DECIMAL(10,3)  NULL,
  `weight_unit`            ENUM('kg','lb','g','oz') NOT NULL DEFAULT 'kg',
  `is_hazardous`           TINYINT(1)     NOT NULL DEFAULT 0,
  `hazmat_class`           VARCHAR(8)     NULL,
  `un_number`              VARCHAR(8)     NULL,
  `proper_shipping_name`   VARCHAR(255)   NULL,
  `packing_group`          ENUM('I','II','III') NULL,
  `is_fragile`             TINYINT(1)     NOT NULL DEFAULT 0,
  `is_stackable`           TINYINT(1)     NOT NULL DEFAULT 1,
  `is_oversize`            TINYINT(1)     NOT NULL DEFAULT 0,
  `is_perishable`          TINYINT(1)     NOT NULL DEFAULT 0,
  `temperature_sensitive`  TINYINT(1)     NOT NULL DEFAULT 0,
  `temp_min`               DECIMAL(5,1)   NULL,
  `temp_max`               DECIMAL(5,1)   NULL,
  `temp_unit`              ENUM('C','F')  NOT NULL DEFAULT 'C',
  `hs_code`                VARCHAR(16)    NULL,
  `country_of_origin`      VARCHAR(64)    NULL,
  `customs_description`    VARCHAR(255)   NULL,
  `declared_value`         DECIMAL(12,2)  NULL,
  `updated_ts`             TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
                                           ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`stock_id`),
  KEY `idx_hazardous` (`is_hazardous`)
);
